Controllers/ClientesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LavanderiaVJWeb.Data;
using LavanderiaVJWeb.Models;

namespace LavanderiaVJWeb.Controllers
{
    public class ClientesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ClientesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Clientes
        public IActionResult Index()
        {
            var clientes= _context.Clientes.Include(c => c.Distrito).ToList();
            return View(clientes);
        }

        // GET: Clientes/Details/5
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var cliente = _context.Clientes.Include(c => c.Distrito).FirstOrDefault(m => m.Id == id);
            if (cliente == null)
            {
                return NotFound();
            }

            return View(cliente);
        }

        // GET: Clientes/Create
        public IActionResult Create()
        {
            ViewData["DistritoName"] = new SelectList(_context.Distritos, "Id", "Nombre");
            //var distritos = _context.Distritos.ToList
            //ViewBag.Distrito = distritos.Select(d => new SelectListItem(d.Nombre, d.Id.ToString()));
            return View();
        }

        // POST: Clientes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("Id,Nombre,Apellido,TipoDoc,NroDoc,Direccion,Email,DistritoId")] Cliente cliente)
        {
            if (ModelState.IsValid)
            {
                if (_context.Clientes.Any(a => a.NroDoc == cliente.NroDoc))
                {
                    ModelState.AddModelError("NroDoc", "Ya existe un Documento con este número");
                }
                else
                {
                    _context.Add(cliente);
                    _context.SaveChanges();
                    return RedirectToAction(nameof(Index));
                }
            }
            ViewData["DistritoName"] = new SelectList(_context.Distritos, "Id", "Nombre", cliente.DistritoId);
            return View(cliente);
        }

        // GET: Clientes/Edit/5
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cliente = _context.Clientes.Find(id);
            if (cliente == null)
            {
                return NotFound();
            }
            ViewData["DistritoName"] = new SelectList(_context.Distritos, "Id", "Nombre", cliente.DistritoId);
            return View(cliente);
        }

        // POST: Clientes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("Id,Nombre,Apellido,TipoDoc,NroDoc,Direccion,Email,DistritoId")] Cliente cliente)
        {
            if (id != cliente.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                // Buscar si existe otro cliente con el mismo número de documento
                var existingCliente = _context.Clientes.FirstOrDefault(a => a.NroDoc == cliente.NroDoc && a.Id != cliente.Id);

                if (existingCliente != null)
                {
                    // Si se encuentra otro cliente con el mismo número de documento, mostrar error
                    ModelState.AddModelError("NroDoc", "Ya existe un cliente con este número de documento.");
                }
                else
                {
                    // Si no hay duplicados, actualizar el cliente y guardar los cambios
                    _context.Update(cliente);
                    _context.SaveChanges();
                    return RedirectToAction(nameof(Index));
                }
            }
            ViewData["DistritoName"] = new SelectList(_context.Distritos, "Id", "Nombre");
            return View(cliente);
        }

        // GET: Clientes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cliente = await _context.Clientes
                .Include(c => c.Distrito)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (cliente == null)
            {
                return NotFound();
            }

            return View(cliente);
        }

        // POST: Clientes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var cliente = await _context.Clientes.FindAsync(id);
            if (cliente != null)
            {
                _context.Clientes.Remove(cliente);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        //private bool ClienteExists(int id)
        //{
        //    return _context.Clientes.Any(e => e.Id == id);
        //}
    }
}

Controllers/ServicioController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using LavanderiaVJWeb.Data;
using Microsoft.AspNetCore.Mvc.Rendering;
using LavanderiaVJWeb.Models;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc.ModelBinding;

namespace LavanderiaVJWeb.Controllers
{
    public class ServicioController : Controller
    {

        private readonly ApplicationDbContext _context;

        public ServicioController(ApplicationDbContext c)
        {
            _context = c;
        }

        public IActionResult Registro()
        {
            //aca se ve el formulario de registro de almacen
            ViewBag.fecha = System.DateTime.Today.ToShortDateString();
            ViewBag.clientes = listarClientes().Select(client => new SelectListItem(client.NroDoc + " " + client.Nombre + " " + client.Apellido, client.Id.ToString()));
            return View();
        }
        [HttpPost]
        public IActionResult Registro(Ticket objTk)
        {
            ViewBag.fecha = System.DateTime.Now;
            ViewBag.clientes = listarClientes().Select(client => new SelectListItem(client.NroDoc + " " + client.Nombre + " " + client.Apellido, client.Id.ToString()));
            //aca se registra el nuevo servicio(ticket) a guardar en almacen
            //revisar si la boleta ya esta registrada
            var nroBoleta = objTk.TkNroBoleta;
            if (checkTicket(nroBoleta) || !ModelState.IsValid || objTk.AlmacenId == 0)
            {
                // si se ingresa una boleta duplicada se activa este metodo y se da el mensaje de error
                if (checkTicket(nroBoleta))
                {
                    ModelState.AddModelError("TkNroBoleta", "Esta boleta ya esta registrada");
                }
                if (objTk.AlmacenId == 0)
                {
                    ModelState.AddModelError("AlmacenId", "Escoja un almacen");
                }
                return View(objTk);
            }
            else
            {
                ViewBag.clientes = listarClientes();
                //se guarda la fecha de 
                objTk.TkFechaIngreso = System.DateTime.Now;
                //asigna por defecto estado "En espera"
                objTk.EstadoId = 1;
                _context.Add(objTk);
                //USAR PARA VER INFO DEL OBJ SIN GUARDAR A LA DB
                // return Json(objTk);
                _context.SaveChanges();
                return RedirectToAction("Listado", objTk);
            }
        }
        public IActionResult Borrarboleta(int? boleta)
        {
            Ticket objTk = new Ticket();
            objTk = _context.Tickets.Find(boleta);
            if (boleta.HasValue)
            {
                _context.Remove(objTk);
                _context.SaveChanges();
                return RedirectToAction("Index", "Home");
            }
            else
            {
                return Json(objTk);
            }
        }

        public IActionResult Listado(Ticket objTk)
        {
            //lista los servicios agregados al ticket
            //permite revisar agregar nuevos servicios o quitarlos del ticket a guardar
            ViewBag.NroBoleta = objTk.TkNroBoleta;
            ViewBag.idBol = objTk.Id;
            var ListaServicios = listarServicios().Where(x => x.TicketId == objTk.Id).ToList();
            // return Json(ListaServicios);
            return View(ListaServicios);
        }

        public IActionResult Detalle(int boleta)
        {
            //recibe los datos para mostrar info del ticket al que se le añaden los servicios
            var objTicket = _context.Tickets.Find(boleta);
            // var objServ = ;
            // return Json(objTicket);
            ViewBag.idboleta = objTicket.Id;
            ViewBag.ServiciosDisponibles = listarServDispo().Select(serv => new SelectListItem(serv.NombreSer, serv.Id.ToString()));
            return View();
        }
        [HttpPost]
        public IActionResult Detalle(Servicio detServ, int idboleta)
        {
            var objTicket = _context.Tickets.Find(idboleta);
            // ViewBag.idboleta = objTicket.Id;
            detServ.TicketId = idboleta;
            if (ModelState.IsValid)
            {
                Debug.WriteLine("entro al if de Detalle");
                // return Json(detServ);
                _context.Add(detServ);
                _context.SaveChanges();
                return RedirectToAction("Listado", objTicket);
            }
            else
            {

                
                Debug.WriteLine("entro al else de Detalle");
                if (detServ.PrecServicio <= 0)
                {
                    Debug.WriteLine("entro al if dentro del else");
                    ModelState.AddModelError("PrecServicio", "El precio debe ser mayor que 0");
                }
                return View(detServ);
            }
        }



        
        public IActionResult Confirmacion(int boleta)
        {
            ViewBag.nroboleta = boleta;
            var objBoleta = _context.Tickets.Find(boleta);
            // return Json(objBoleta);
            return View();
        }
        [HttpPost]
        public IActionResult Confirmacion(int boleta, Ticket objTicket)
        {
            var objBoleta = _context.Tickets.Find(boleta);
            var suma = _context.Servicios.Include(x => x.ticket).Where(y => y.TicketId == boleta).Sum(z => z.PrecServicio);
            objBoleta.TkPagoTotal = suma;
            objBoleta.TkFechaEntrega = objTicket.TkFechaEntrega;
            // return Json(objBoleta);
            _context.Update(objBoleta);
            _context.SaveChanges();
            return RedirectToAction("Index", "Home");
        }

        public IActionResult ModificarEstadoServicio(Ticket objTicket)
        {
            var Estado = true;
            ViewBag.Peticion = Estado;
            if (objTicket.TkNroBoleta != 0)//SE BUSCA EL TICKET
            {
                objTicket = _context.Tickets.Include(x => x.Cliente).Include(y => y.Estado).Where(x => x.TkNroBoleta == objTicket.TkNroBoleta).FirstOrDefault();//BUSCAR
                if (objTicket == null)//NO ENCUENTRA EL TICKET
                {
                    ModelState.AddModelError("TkNroBoleta", "Boleta no encontrada");
                    Estado = true; // si no existe manda a formulario GET
                }
                else//ENCUENTRA EL TICKET
                {
                    ViewBag.NUMEROBOLETA = objTicket.TkNroBoleta;
                    ViewBag.CLIENTE = objTicket.Cliente.Nombre + " " + objTicket.Cliente.Apellido + " " + objTicket.Cliente.NroDoc;
                    ViewBag.ESTADOS = _context.Estados.ToList().Select(x => new SelectListItem(x.NombreEstado, x.Id.ToString()));
                    Estado = false; // si existe manda a formulario POST
                }
                ViewBag.Peticion = Estado;
                // return Json(objTicket);
                return View(objTicket);
            }
            else//NO SE BUSCA TICKET = PRIMERA VEZ QUE ENTRA
            {
                ViewBag.Peticion = Estado;
                return View();
            }
        }

        [HttpPost]
        public IActionResult ModificarEstadoServicio(int nroboleta, Ticket objBoleta)
        {
            var objayuda = new Ticket();
            ViewBag.Peticion = true;
            objayuda = _context.Tickets.Include(x => x.Cliente).Include(y => y.Estado).Where(x => x.TkNroBoleta == objBoleta.TkNroBoleta).FirstOrDefault();//BUSCAR
            ViewBag.NUMEROBOLETA = objayuda.TkNroBoleta;
            ViewBag.CLIENTE = objayuda.Cliente.Nombre + " " + objayuda.Cliente.Apellido + " " + objayuda.Cliente.NroDoc;
            ViewBag.ESTADOS = _context.ServiciosDisponibles.ToList().Select(x => new SelectListItem(x.NombreSer, x.Id.ToString()));
            objayuda.EstadoId = objBoleta.EstadoId;
            _context.Update(objayuda);
            _context.SaveChanges();
            return View();
        }

        public IActionResult VerEstadoServicio(Ticket objTicket)
        {
            var Estado = true;
            ViewBag.Peticion = Estado;
            if (objTicket.TkNroBoleta != 0)//SE BUSCA EL TICKET
            {
                objTicket = _context.Tickets.Include(x => x.Cliente).Include(x => x.Servicios).Include(y => y.Estado).Where(x => x.TkNroBoleta == objTicket.TkNroBoleta).FirstOrDefault();//BUSCAR

                if (objTicket == null)//NO ENCUENTRA EL TICKET
                {
                    ModelState.AddModelError("TkNroBoleta", "Boleta no encontrada");
                    Estado = true; // si no existe manda a formulario GET
                }
                else//ENCUENTRA EL TICKET
                {
                    ViewBag.NUMEROBOLETA = objTicket.TkNroBoleta;
                    ViewBag.CLIENTE = objTicket.Cliente.Nombre + " " + objTicket.Cliente.Apellido + " " + objTicket.Cliente.NroDoc;
                    ViewBag.ESTADOS = objTicket.Estado.NombreEstado;
                    ViewBag.PRECIOTOTAL = objTicket.TkPagoTotal;
                    ViewBag.FECHAENTREGA = objTicket.TkFechaEntrega.Value.ToShortDateString();
                    Estado = false; // si existe manda a formulario POST
                }
                ViewBag.Peticion = Estado;
                // return Json(objTicket);
                return View(objTicket);
            }
            else//NO SE BUSCA TICKET = PRIMERA VEZ QUE ENTRA
            {
                ViewBag.Peticion = Estado;
                return View();
            }
        }

        [HttpPost]
        public IActionResult VerEstadoServicio(int nroboleta, Ticket objBoleta)
        {
            var objayuda = new Ticket();
            ViewBag.Peticion = true;
            objayuda = _context.Tickets.Include(x => x.Cliente).Include(y => y.Estado).Where(x => x.TkNroBoleta == objBoleta.TkNroBoleta).FirstOrDefault();//BUSCAR

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LavanderiaVJWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" type="text/css" href="css/bootstrap-responsive.css" />
    <link rel="icon" type="image/png" href="imagenes/ico/burbujas01.png" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                
                <a class="navbar-brand" href="/Home/Index">
                    <img height="80px" width="auto" src="~/images/LogoBurbujas1.png" />
                </a>
                

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li>
                            <a class="nav-link" asp-controller="Servicio" asp-action="serviciosPendientes">SERVICIOS PENDIENTES</a>
                        </li>


                        <li class="nav-item dropdown">

                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                MANTENIMIENTO DE SERVICIOS
                            </a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a class="dropdown-item text-dark" asp-controller="Servicio" asp-action="Registro">Registrar Servicio y Prendas de Lavandería</a>
                                </li>
                                <li>
                                    <a class="dropdown-item text-dark" asp-controller="Servicio" asp-action="servicios">Listar Servicios</a>
                                </li>
                                
                                <li>
                                    <a class="dropdown-item text-dark" asp-controller="Servicio" asp-action="serviciosRealizados">Reportes de servicios</a>
                                </li>
                                <li>
                                    <a class="dropdown-item text-dark" asp-controller="Servicio" asp-action="ModificarEstadoServicio">Actualizar Estado de Servicio</a>
                                </li>
                            </ul>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                ATENCIÓN DE CLIENTES
                            </a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a class="dropdown-item text-dark" asp-controller="Clientes" asp-action="Create">Registrar Cliente</a>
                                </li>
                                <li>
                                    <a class="dropdown-item text-dark" asp-controller="Clientes" asp-action="Index">Listar Clientes registrados</a>
                                </li>
                                <li>
                                    <a class="dropdown-item text-dark" asp-controller="Servicio" asp-action="VerEstadoServicio">Visualizar detalle y estado de servicios</a>
                                </li>
                            </ul>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Cuenta" asp-action="Registro">CREAR CUENTA</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Cuenta" asp-action="Acceso">INICIAR SESIÓN</a>
                        </li>
                        
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="ServiciosDisponibles" asp-action="Index">SERVICIOS QUE SE BRINDA (ADMIN)</a>
                        </li>
                    </ul>
                    
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - LavanderiaVJWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>